### ISSUE TITLE
Blocage impression des documents -Fiche de poste, Groupement, Document Unique

### ISSUE THREAD

**Issue by lmag** [Evarisk/WP-Digirisk#57]
Nous avons rencontré une erreur lors de l’impression des documents sur des installations de serveurs dédiés : 

PHP Fatal error:  Uncaught exception 'DigiOdfException' with message 'Error during file export addFromString' in /var/www/digirisk/wp-content/plugins/digirisk/core/external/odtPhpLibrary/odf.php:281\nStack trace:\n#0 /var/www/digirisk/wp-content/plugins/digirisk/core/external/odtPhpLibrary/odf.php(264): DigiOdf->_save()\n#1 /var/www/digirisk/wp-content/plugins/digirisk/modules/document/class/document.class.php(233): DigiOdf->saveToDisk('/var/www/digiri...')\n#2 /var/www/digirisk/wp-content/plugins/digirisk/modules/document/class/document.class.php(446): digi\\Document_Class->generate_document('/var/www/digiri...', Array, 'digi-society/7/...')\n#3 /var/www/digirisk/wp-content/plugins/digirisk/modules/duer/class/duer-generate.class.php(62): digi\\Document_Class->create_document(Object(digi\\Society_Model), Array, Array)\n#4 /var/www/digirisk/wp-content/plugins/digirisk/modules/duer/action/duer.action.php(87): digi\\DUER_Generate_Class->generate(Array)\n#5 [internal function]: digi\\DUER_Action->callback_ajax_generate_duer('')\n#6 /var/www/di in /var/www/digirisk/wp-content/plugins/digirisk/core/external/odtPhpLibrary/odf.php on line 281, referer: http://192.168.0.2/digirisk/wp-admin/admin.php?page=digirisk-simple-risk-evaluation

**Comment by lmag** [comment]
L'administrateur système à résolu ce problème de la façon suivante 👍 

> Merci encore pour le temps passé hier ensemble.
> Le problème a été réglé par une mise à jour des extensions zlib et zip via la procédure suivante :
> 1 Step - Install a required extension 
> sudo apt-get install libz-dev -y
> 2 Step - Install the PHP extension 
> pecl install zlib zip
> 3 Step - Restart your Apache
> sudo /etc/init.d/apache2 restart
> Si jamais vous avez un client qui a un problème similaire, cette procédure le sortira de l’embarras.

Merci pour le retour 👍 
Nous faisons les tests d'installation de DigiRisk sur ces configurations qui sont souvent "prete pour WordPress" : 
https://www.evarisk.com/document-unique-logiciel/documentation/introduction/pre-requis-digirisk/
